package de.juffel.datetagger;

import java.text.SimpleDateFormat;
import java.util.Date;

import android.support.v4.app.Fragment;
import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import de.juffel.datetagger.DateTaggerContract.TagEntry;

public class HomeFragment extends Fragment {

    private SQLiteDatabase db;
    
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        // initialize db stuff
        DateTaggerDbHelper mDbHelper = new DateTaggerDbHelper(getActivity());
        db = mDbHelper.getWritableDatabase();

        return inflater.inflate(R.layout.fragment_home, container, false);
    }
    
    public void addTag() {
//    	EditText editText = (EditText) findViewById(R.id.edit_message);
//    	addTag(editText.getText().toString());
//    	// empty EditText
//    	editText.setText("");
    }

    private Long addTag(String tag) {
    	// do not add empty tags
    	if (tag.equals("")) {
    		return null;
    	}
    	ContentValues values = new ContentValues();
    	
    	// get current date
    	String date = getCurrentDateTimeString();

    	// id will be autogenerated (hopefluffy)
    	values.put(TagEntry.COLUMN_NAME_CONTENT, tag);
    	values.put(TagEntry.COLUMN_NAME_DATE, date);

    	// the 2nd parameter is a nullable column (why ? i dont know)
    	return db.insert(TagEntry.TABLE_NAME, TagEntry.COLUMN_NAME_CONTENT, values);
    }

    private String getCurrentDateTimeString() {
    	SimpleDateFormat iso8601Format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    	return iso8601Format.format(new Date());
    }

}
